#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf constant/polyMesh/boundary > /dev/null 2>&1
rm -rf patch* > /dev/null 2>&1

find -iname "*~" | xargs rm -rf
