#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanTimeDirectories
rm -rf processor* > /dev/null 2>&1
rm -rf probes* > /dev/null 2>&1
rm -rf forces* > /dev/null 2>&1
rm -rf patch* > /dev/null 2>&1

rm -rf system/machines \
    constant/cellToRegion \
    constant/polyMesh/*Zones \
    constant/polyMesh/sets/ \
    VTK \
    > /dev/null 2>&1

find -iname "*~" | xargs rm -rf
