#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication -llog.blockMeshSolid blockMesh -region solid

runApplication setSet -batch setBatch
runApplication setsToZones -noFlipMap

runApplication -llog.setSetSolid setSet -batch setBatchSolid -region solid
runApplication -llog.setsToZonesSolid setsToZones -noFlipMap -region solid

cp -r constant/solid/boundary constant/solid/polyMesh
cp -r constant/boundary constant/polyMesh

runApplication decomposePar
runApplication -llog.decomposeParSolid decomposePar -region solid

runParallel transonicMRFCHTDyMFoam 4

runApplication reconstructPar -latestTime
runApplication -llog.reconstructParSolid reconstructPar -latestTime -region solid
