#!/bin/sh

wmake libso godunovFlux
wmake libso timeStepping
wmake transonicMRFDyMFoam
wmake transonicMRFCHTDyMFoam
wmake transonicMRFFSIDyMFoam
wmake transonicSteadySRFFoam
wmake transonicUnsteadyMRFDyMFoam

